final products = [
  {
    'id': '0',
    'title': 'Dress Material',
    'price': 650,
    'imageUrl': 'assets/images/1.jpg',
    'sizes': [38, 40, 42, 44],
  },
  {
    'id': '1',
    'title': 'Dupatta',
    'price': 250,
    'imageUrl': 'assets/images/dupatta.jpg',
    'sizes': [38, 40, 42, 44],
  },
  {
    'id': '2',
    'title': 'Cotton Dresses',
    'price': 750,
    'imageUrl': 'assets/images/cotton_dress.jpg',
    'sizes': [38, 40, 42, 44],
  },
  {
    'id': '3',
    'title': 'Sharara Suits',
    'price': 1200,
    'imageUrl': 'assets/images/sharara.jpg',
    'sizes': [38, 40, 42, 44],
  },
  {
    'id': '3',
    'title': 'Lehenga Cholis',
    'price': 3000,
    'imageUrl': 'assets/images/Lehenga.jpg',
    'sizes': [38, 40, 42, 44],
  },
  {
    'id': '3',
    'title': 'Maxi Kurtis',
    'price': 1000,
    'imageUrl': 'assets/images/Maxi_Kurtis_1.jpg',
    'sizes': [38, 40, 42, 44],
  },
  {
    'id': '3',
    'title': 'Salwar Suits',
    'price': 950,
    'imageUrl': 'assets/images/salwar_suits.jpg',
    'sizes': [38, 40, 42, 44],
  },
  {
    'id': '3',
    'title': 'Indo-Western Dresses',
    'price': 860,
    'imageUrl': 'assets/images/Indo_Western_Dresses.jpg',
    'sizes': [38, 40, 42, 44],
  },
  {
    'id': '3',
    'title': 'Anarkali Suits',
    'price': 3300,
    'imageUrl': 'assets/images/Anarkali_Suits.jpg',
    'sizes': [38, 40, 42, 44],
  },
];
